---
# file: roles/common/tasks/main.yml

- name: be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: Install common packages
  sudo: yes
  action: apt pkg={{ item }} state=installed
  with_items:
    - build-essential
    - curl
    - fail2ban
    - git-core
    - htop
    - iftop
    - iotop
    - iperf
    - libcurl4-openssl-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - python-software-properties
    - smartmontools
    - vim
    - zlib1g-dev
    - zlib1g-dev

- name : Create deployer group
  group: name=deployer gid=450 state=present

- name: setup deployer user
  user: name=deployer uid=450 group=deployer createhome=yes shell=/bin/bash state=present
  register: deployuser

- name: Lock the deploy user account
  shell: passwd -l deployer
  when: deployuser.changed
